#!/usr/bin/env php
<?php

use Cinch\Console\Application;
use Cinch\Console\ConsoleIo;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

require_once __DIR__ . '/vendor/autoload.php';

if (PHP_SAPI !== 'cli')
    throw new RuntimeException("cinch CLI only supports 'cli' SAPI");

$io = new ConsoleIo(new ArgvInput(), new ConsoleOutput());
$app = new Application('cinch', $io);

try {
    $env = $app->loadEnv(__DIR__);

    if (!($version = getenv('CINCH_VERSION')))
        throw new RuntimeException('Missing CINCH_VERSION environment variable');

    $app->setVersion($version);
    $io->debug("cinch $version using $env environment");
    $exitCode = $app->run();
}
catch (Exception $e) {
    $exitCode = 255;
    $app->renderThrowable($e, $io->getOutput()->getErrorOutput());
}
finally {
    if ($exitCode = min(255, $exitCode))
        $io->setIndent()->debug("application exit code $exitCode");

    exit($exitCode);
}