#!/usr/bin/env php
<?php

use Cinch\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;

require_once __DIR__ . '/vendor/autoload.php';

if (PHP_SAPI !== 'cli')
    throw new RuntimeException("cinch CLI only supports 'cli' SAPI");

$application = new Application();
$application->setAutoExit(false);
$output = new ConsoleOutput(OutputInterface::VERBOSITY_VERY_VERBOSE);

try {
    $exitCode = $application->run(output: $output);
}
catch (Exception $e) {
    $exitCode = 255; // uncaught exception, must be from Application since Commands are handled
    $application->renderThrowable($e, $output->getErrorOutput());
}

$exitCode = min(255, $exitCode);
if ($exitCode)
    $output->writeln("<fg=blue>[application exit code $exitCode]</>");

exit($exitCode);