version: '3.8'

services:
  mysql:
    image: mysql:oracle
    container_name: cinch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "6000:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/bootstrap.sql:$DB_BOOTSTRAP
      - ./docker/server.key:$MYDATA/server-key.pem
      - ./docker/server.crt:$MYDATA/server-cert.pem
      - ./docker/root.crt:$MYDATA/ca.pem

  postgres:
    image: postgres:latest
    container_name: cinch-postgres
    environment:
      PGDATA:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "6001:5432"
    volumes:
      - pgsql:$PGDATA
      - ./docker/postgres/bootstrap.sql:$DB_BOOTSTRAP
      - ./docker/postgres/postgresql.conf:$PGDATA/postgresql.conf
      - ./docker/postgres/pg_hba.conf:$PGDATA/pg_hba.conf
      - ./docker/server.key:$PGDATA/server.key
      - ./docker/server.crt:$PGDATA/server.crt
      - ./docker/root.crt:$PGDATA/root.crt

  # https://hub.docker.com/_/microsoft-azure-sql-edge
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: cinch-mssql
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ZC34!kj98
    ports:
      - "1433:1433"
    volumes:
      - mssql:$MSDATA

volumes:
  mysql:
  pgsql:
  mssql: