name: PHP CS Fixer

on:
#  push:
#    branches: [ "action-test" ]
  pull_request:
    branches: [ "action-test" ]

# permissions:
#  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install composer packages
        run: composer install -qn

      - name: Run PHP-CS-Fixer Style
        run: |
          ./vendor/bin/php-cs-fixer fix --config=./php_cs.php --allow-risky=no
          rm -f ./.php-cs-fixer.cache

      - name: Push Changes
        run: |
          date > generated.txt
          git add .
          git commit -m "Apply PHP-CS-Fixer changes"
          git push

#          git config user.name andrewchernow
#          git config user.email achernow@gmail.com

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Apply PHP-CS-Fixer changes
