name: PHP CS Fixer

on:
  push:
    branches: [ "cs-fix-test" ]
  pull_request:
    branches: [ "cs-fix-test" ]

# permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Run PHP-CS-Fixer Style
      run: ./vendor/bin/php-cs-fixer fix --config=./php_cs.php --allow-risky=no

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply PHP-CS-Fixer changes
